version: "3.9"
services:
  db:
    profiles: ["dev", "db"]
    image: postgis/postgis:14-master
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_DB: "db"
      POSTGRES_USER: "db"
      POSTGRES_PASSWORD: "db"
    working_dir: /app
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - 127.0.0.1:4021:5432
    command: "postgres -c max_connections=300 -c shared_buffers=512MB -c effective_cache_size=4GB -c work_mem=16MB -c maintenance_work_mem=512MB -c random_page_cost=1.1 -c temp_file_limit=10GB -c log_min_duration_statement=200ms -c idle_in_transaction_session_timeout=10s -c lock_timeout=1s -c statement_timeout=60s -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.max=10000 -c pg_stat_statements.track=all -c wal_level=logical -c max_replication_slots=10 -c max_wal_senders=10 -c log_min_messages=fatal"

#-----------------------------------------------------------------------------
networks:
  sapi_default:

# -----------------------------------------------------------------------------
volumes:
  db_data: